# エディターの補完を設定スキーマに合わせて取得
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
format = "[$path]($style) "
truncation_length = 8
truncation_symbol = "..."
truncate_to_repo = false

[git_branch]
format = "on [$symbol$branch]($style) "
